### ISSUE TITLE
model parameter changes always result in NPE

### ISSUE THREAD

**Issue by jjYBdx4IL** [Simsilica/SimArboreal-Editor#5]
using the latest release, whenever I change a model parameter, like enabling leaves, an NPE is thrown. Win 10 amd64, oracle jdk 10.0.1.

SCHWERWIEGEND: Uncaught exception thrown in Thread[LWJGL Renderer Thread,5,main]
java.lang.NullPointerException
        at com.jme3.util.BufferUtils.destroyDirectBuffer(BufferUtils.java:1298)
        at com.jme3.util.BufferUtils.destroyDirectBuffer(BufferUtils.java:1303)
        at com.simsilica.arboreal.TreeBuilderReference.releaseMesh(TreeBuilderReference.java:289)
        at com.simsilica.arboreal.TreeBuilderReference.releaseGeometry(TreeBuilderReference.java:280)
        at com.simsilica.arboreal.TreeBuilderReference$LevelGeometry.release(TreeBuilderReference.java:502)
        at com.simsilica.arboreal.TreeBuilderReference.apply(TreeBuilderReference.java:243)
        at com.simsilica.builder.Builder.applyUpdates(Builder.java:274)
        at com.simsilica.builder.BuilderState.update(BuilderState.java:100)
        at com.jme3.app.state.AppStateManager.update(AppStateManager.java:287)
        at com.jme3.app.SimpleApplication.update(SimpleApplication.java:239)
        at com.jme3.system.lwjgl.LwjglAbstractDisplay.runLoop(LwjglAbstractDisplay.java:151)
        at com.jme3.system.lwjgl.LwjglDisplay.runLoop(LwjglDisplay.java:185)
        at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:228)
        at java.base/java.lang.Thread.run(Thread.java:844)

03:39:45,666 INFO  [MeshBuilder] Creating a mesh with:6020 vertexes and:10488 triangles.

Exception: java.lang.NullPointerException thrown from the UncaughtExceptionHandler in thread "LWJGL Renderer Thread"
AL lib: (EE) alc_cleanup: 1 device not closed

**Comment by pspeed42** [comment]
What version of Java are you using?

**Comment by jjYBdx4IL** [comment]
oracle jdk 10.0.1, amd64, windows 10 latest

**Comment by pspeed42** [comment]
I think jme has problems with that Java.  You might try an older one.
